sonar.projectKey=Systems-SAST-Testing
sonar.projectName=Systems-SAST-Testing
sonar.projectVersion=1.0

sonar.sources=/mnt/c/Users/anaudiyal/official/0.projects/api_pentesting/sonar/sample_code/.
sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarqube.aws.1-stop.biz
sonar.login=sqp_
